[H[J[3J[96m[1mconfigure[0m [[92minfo[0m] : Execute "make clean" from "makefile.gen"
[96m[1mconfigure[0m [[92minfo[0m] : Execute "make clean" from "test/makefile.gen"
[H[J[3J  libft.a [           ] 0%
[H[J[3J  libft.a [           ] 2%
[H[J[3J  libft.a [           ] 5%
[H[J[3J  libft.a [           ] 7%
[H[J[3J  libft.a [#          ] 10%
[H[J[3J  libft.a [#          ] 12%
[H[J[3J  libft.a [#          ] 15%
[H[J[3J  libft.a [#          ] 17%
[H[J[3J  libft.a [##         ] 20%
[H[J[3J  libft.a [##         ] 23%
[H[J[3J  libft.a [##         ] 25%
[H[J[3J  libft.a [##         ] 28%
[H[J[3J  libft.a [###        ] 30%
[H[J[3J  libft.a [###        ] 33%
[H[J[3J  libft.a [###        ] 35%
[H[J[3J  libft.a [###        ] 38%
[H[J[3J  libft.a [####       ] 41%
[H[J[3J  libft.a [####       ] 43%
[H[J[3J  libft.a [####       ] 46%
[H[J[3J  libft.a [####       ] 48%
[H[J[3J  libft.a [#####      ] 51%
[H[J[3J  libft.a [#####      ] 53%
[H[J[3J  libft.a [#####      ] 56%
[H[J[3J  libft.a [#####      ] 58%
[H[J[3J  libft.a [######     ] 61%
[H[J[3J  libft.a [######     ] 64%
[H[J[3J  libft.a [######     ] 66%
[H[J[3J  libft.a [######     ] 69%
[H[J[3J  libft.a [#######    ] 71%
[H[J[3J  libft.a [#######    ] 74%
[H[J[3J  libft.a [#######    ] 76%
[H[J[3J  libft.a [#######    ] 79%
[H[J[3J  libft.a [########   ] 82%
[H[J[3J  libft.a [########   ] 84%
[H[J[3J  libft.a [########   ] 87%
[H[J[3J  libft.a [########   ] 89%
[H[J[3J  libft.a [#########  ] 92%
[H[J[3J  libft.a [#########  ] 94%
[H[J[3J  libft.a [#########  ] 97%
[H[J[3J  libft.a [           ] 0%
[H[J[3J  libft.a [########## ] 102%
[H[J[3J  libft.a [########## ] 105%
[H[J[3J  libft.a [########## ] 107%
[H[J[3J  libft.a [###########] 110%
[H[J[3J  libft.a [###########] 112%
[H[J[3J  libft.a [###########] 115%
[H[J[3J  libft.a [###########] 117%
[H[J[3J  libft.a [############] 120%
[H[J[3J  libft.a [############] 123%
[H[J[3J  libftprintf.a [#          ] 16%
[H[J[3J  libftprintf.a [###        ] 33%
[H[J[3J  libftprintf.a [#####      ] 50%
[H[J[3J  libftprintf.a [######     ] 66%
[H[J[3J  libftprintf.a [########   ] 83%
[H[J[3J  libftprintf.a [########## ] 100%
[H[J[3J  list.a [           ] 0%
[H[J[3J  list.a [###        ] 33%
[H[J[3J  list.a [######     ] 66%
[96m[1mconfigure[0m [[92minfo[0m] : Found X11 include path directory: /usr/include
[96m[1mconfigure[0m [[92minfo[0m] : Generate "makefile.gen" from template "makefile.mk"
[96m[1mconfigure[0m [[92minfo[0m] : Generate "test/makefile.gen" from template "test/makefile.mk"
[96m[1mconfigure[0m [[92minfo[0m] : Execute "make all" from file "makefile.gen"
[96m[1mconfigure[0m [[92minfo[0m] : Execute "make all" from file "test/makefile.gen"
╔══════════════════════════╗
║ ✅ Compiled Successfully!║
╚══════════════════════════╝
